#!/bin/sh

# schaal @it
#
# Simple script to update SpamAssassin

SYSLOG_TAG=sa-update

compile=0

logger -d -t $SYSLOG_TAG "Start SA-Update"

sa-update --nogpg
retval="$?"
if [ $retval -eq 0 ]; then compile=1; fi


sa-update --nogpg --channel updates.spamassassin.org
retval="$?"
if [ $retval -eq 0 ]; then compile=1; fi

sa-update --nogpg --channel sa.schaal-it.net
retval="$?"
if [ $retval -eq 0 ]; then compile=1; fi

#sa-update --nogpg --channel sought.rules.yerp.org
#retval="$?"
#if [ $retval -eq 0 ]; then compile=1; fi

#sa-update --nogpg --channel spamassassin.heinlein-support.de
#retval="$?"
#if [ $retval -eq 0 ]; then compile=1; fi

if [ $compile -eq 1 ]; then
        logger -d -t $SYSLOG_TAG "SA-Update found"
        sa-compile
        /etc/init.d/spamassassin restart
else
        logger -d -t $SYSLOG_TAG "No SA-Update found"
fi
